-- ==========================================
-- Supabase Schema Migration & Data Migration Script
-- ==========================================

-- 1. Create normalized master tables
CREATE TABLE IF NOT EXISTS public.transaction_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL DEFAULT 'other',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.payment_methods ADD COLUMN IF NOT EXISTS type TEXT NOT NULL DEFAULT 'other';

CREATE TABLE IF NOT EXISTS public.parent_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.child_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_category_id BIGINT NOT NULL REFERENCES public.parent_categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT child_categories_parent_category_id_name_unique UNIQUE (parent_category_id, name)
);

CREATE TABLE IF NOT EXISTS public.card_types (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID DEFAULT auth.uid(),
  name TEXT NOT NULL,
  payment_method TEXT,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create card settings table (referencing payment_methods)
CREATE TABLE IF NOT EXISTS public.card_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid(),
  payment_method_id BIGINT REFERENCES public.payment_methods(id) ON DELETE CASCADE,
  card_name TEXT NOT NULL UNIQUE,
  is_credit_card BOOLEAN NOT NULL DEFAULT true,
  closing_day INTEGER NOT NULL DEFAULT 15,
  payment_month_offset INTEGER NOT NULL DEFAULT 1,
  payment_day INTEGER NOT NULL DEFAULT 10,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create Bank Accounts & Bank Balances tables (referencing payment_methods and bank_accounts)
CREATE TABLE IF NOT EXISTS public.bank_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid(),
  payment_method_id BIGINT REFERENCES public.payment_methods(id) ON DELETE SET NULL,
  account_name TEXT NOT NULL UNIQUE,
  bank_name TEXT,
  account_number TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bank_balances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid(),
  bank_account_id BIGINT NOT NULL REFERENCES public.bank_accounts(id) ON DELETE CASCADE,
  record_date DATE NOT NULL,
  balance INTEGER NOT NULL,
  memo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Create normalized transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid(),
  date DATE NOT NULL,
  type_id BIGINT REFERENCES public.transaction_types(id),
  payment_method_id BIGINT REFERENCES public.payment_methods(id),
  parent_category_id BIGINT REFERENCES public.parent_categories(id),
  child_category_id BIGINT REFERENCES public.child_categories(id),
  amount INTEGER,
  location TEXT,
  memo TEXT,
  note TEXT,
  tag TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Populate master records from transactions_work
INSERT INTO public.transaction_types (name)
SELECT DISTINCT TRIM(type)
FROM public.transactions_work
WHERE type IS NOT NULL AND TRIM(type) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.payment_methods (name, type)
SELECT DISTINCT
  TRIM(payment_method) AS name,
  CASE
    WHEN TRIM(payment_method) LIKE '%現金%' OR LOWER(TRIM(payment_method)) LIKE '%cash%' THEN 'cash'
    WHEN TRIM(payment_method) LIKE '%銀行%' OR TRIM(payment_method) LIKE '%口座%' OR TRIM(payment_method) LIKE '%預金%' OR LOWER(TRIM(payment_method)) LIKE '%bank%' THEN 'bank_account'
    WHEN TRIM(payment_method) LIKE '%カード%' OR TRIM(payment_method) LIKE '%クレカ%' OR LOWER(TRIM(payment_method)) LIKE '%card%' OR LOWER(TRIM(payment_method)) LIKE '%visa%' OR LOWER(TRIM(payment_method)) LIKE '%jcb%' THEN 'credit_card'
    ELSE 'other'
  END AS type
FROM public.transactions_work
WHERE payment_method IS NOT NULL AND TRIM(payment_method) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.parent_categories (name)
SELECT DISTINCT TRIM(parent_category)
FROM public.transactions_work
WHERE parent_category IS NOT NULL AND TRIM(parent_category) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.child_categories (name, parent_category_id)
SELECT DISTINCT
  TRIM(tw.child_category) AS name,
  pc.id AS parent_category_id
FROM public.transactions_work tw
LEFT JOIN public.parent_categories pc ON pc.name = TRIM(tw.parent_category)
WHERE tw.child_category IS NOT NULL AND TRIM(tw.child_category) <> '' AND pc.id IS NOT NULL
ON CONFLICT (parent_category_id, name) DO NOTHING;

-- 6. Copy records from transactions_work to normalized transactions
INSERT INTO public.transactions (
  user_id,
  date,
  type_id,
  payment_method_id,
  parent_category_id,
  child_category_id,
  amount,
  location,
  memo,
  note,
  tag,
  created_at
)
SELECT
  tw.user_id,
  tw.date,
  tt.id AS type_id,
  pm.id AS payment_method_id,
  pc.id AS parent_category_id,
  cc.id AS child_category_id,
  tw.amount,
  tw.location,
  tw.memo,
  tw.note,
  tw.tag,
  tw.created_at
FROM public.transactions_work tw
LEFT JOIN public.transaction_types tt ON tt.name = TRIM(tw.type)
LEFT JOIN public.payment_methods pm ON pm.name = TRIM(tw.payment_method)
LEFT JOIN public.parent_categories pc ON pc.name = TRIM(tw.parent_category)
LEFT JOIN public.child_categories cc ON cc.name = TRIM(tw.child_category) AND cc.parent_category_id = pc.id;
