-- ==========================================
-- Supabase Schema Migration & Data Migration Script
-- ==========================================

-- 1. Create normalized master tables
CREATE TABLE IF NOT EXISTS public.transaction_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.parent_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.child_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_category_id BIGINT REFERENCES public.parent_categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create normalized transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid(),
  date DATE NOT NULL,
  type_id BIGINT REFERENCES public.transaction_types(id),
  payment_method_id BIGINT REFERENCES public.payment_methods(id),
  parent_category_id BIGINT REFERENCES public.parent_categories(id),
  child_category_id BIGINT REFERENCES public.child_categories(id),
  amount INTEGER,
  location TEXT,
  memo TEXT,
  note TEXT,
  tag TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Populate master records from transactions_work
INSERT INTO public.transaction_types (name)
SELECT DISTINCT TRIM(type)
FROM public.transactions_work
WHERE type IS NOT NULL AND TRIM(type) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.payment_methods (name)
SELECT DISTINCT TRIM(payment_method)
FROM public.transactions_work
WHERE payment_method IS NOT NULL AND TRIM(payment_method) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.parent_categories (name)
SELECT DISTINCT TRIM(parent_category)
FROM public.transactions_work
WHERE parent_category IS NOT NULL AND TRIM(parent_category) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.child_categories (name, parent_category_id)
SELECT DISTINCT
  TRIM(tw.child_category) AS name,
  pc.id AS parent_category_id
FROM public.transactions_work tw
LEFT JOIN public.parent_categories pc ON pc.name = TRIM(tw.parent_category)
WHERE tw.child_category IS NOT NULL AND TRIM(tw.child_category) <> ''
ON CONFLICT DO NOTHING;

-- 4. Copy records from transactions_work to normalized transactions
INSERT INTO public.transactions (
  user_id,
  date,
  type_id,
  payment_method_id,
  parent_category_id,
  child_category_id,
  amount,
  location,
  memo,
  note,
  tag,
  created_at
)
SELECT
  tw.user_id,
  tw.date,
  tt.id AS type_id,
  pm.id AS payment_method_id,
  pc.id AS parent_category_id,
  cc.id AS child_category_id,
  tw.amount,
  tw.location,
  tw.memo,
  tw.note,
  tw.tag,
  tw.created_at
FROM public.transactions_work tw
LEFT JOIN public.transaction_types tt ON tt.name = TRIM(tw.type)
LEFT JOIN public.payment_methods pm ON pm.name = TRIM(tw.payment_method)
LEFT JOIN public.parent_categories pc ON pc.name = TRIM(tw.parent_category)
LEFT JOIN public.child_categories cc ON cc.name = TRIM(tw.child_category);
