'use server';

import { db } from '@/src/db';
import {
  transactions,
  transactionsWork,
  cardSettings,
  transactionTypes,
  paymentMethods,
  parentCategories,
  childCategories,
  bankAccounts,
  bankBalances,
} from '@/src/db/schema';
import { eq, desc, and, sql } from 'drizzle-orm';
import { revalidatePath } from 'next/cache';
import { parseHouseholdCsv } from '@/lib/csv';
import { createClient } from '@/lib/supabase/server';

// Helper to safely get user ID without throwing if Supabase env is unconfigured
async function getSafeUserId(): Promise<string | null> {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    return user?.id || null;
  } catch {
    return null;
  }
}

// Automatically create tables on the application side if they do not exist
export async function initializeAndMigrateDatabase() {
  try {
    // 1. Create normalized master tables
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS public.transaction_types (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS public.payment_methods (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS public.parent_categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS public.child_categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parent_category_id BIGINT NOT NULL REFERENCES public.parent_categories(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT child_categories_parent_category_id_name_unique UNIQUE (parent_category_id, name)
      );
    `);

    // 2. Create card_settings table
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS public.card_settings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL DEFAULT auth.uid(),
        payment_method_id BIGINT REFERENCES public.payment_methods(id) ON DELETE CASCADE,
        card_name TEXT NOT NULL UNIQUE,
        is_credit_card BOOLEAN NOT NULL DEFAULT true,
        closing_day INTEGER NOT NULL DEFAULT 15,
        payment_month_offset INTEGER NOT NULL DEFAULT 1,
        payment_day INTEGER NOT NULL DEFAULT 10,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    // 3. Create bank_accounts & bank_balances tables
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS public.bank_accounts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL DEFAULT auth.uid(),
        payment_method_id BIGINT REFERENCES public.payment_methods(id) ON DELETE SET NULL,
        account_name TEXT NOT NULL UNIQUE,
        bank_name TEXT,
        account_number TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS public.bank_balances (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL DEFAULT auth.uid(),
        bank_account_id BIGINT NOT NULL REFERENCES public.bank_accounts(id) ON DELETE CASCADE,
        record_date DATE NOT NULL,
        balance INTEGER NOT NULL,
        memo TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    // 4. Create normalized transactions table
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS public.transactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id UUID NOT NULL DEFAULT auth.uid(),
        date DATE NOT NULL,
        type_id BIGINT REFERENCES public.transaction_types(id),
        payment_method_id BIGINT REFERENCES public.payment_methods(id),
        parent_category_id BIGINT REFERENCES public.parent_categories(id),
        child_category_id BIGINT REFERENCES public.child_categories(id),
        amount INTEGER,
        location TEXT,
        memo TEXT,
        note TEXT,
        tag TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    // 5. Migrate / save data from transactions_work to normalized transactions
    const saveRes = await saveWorkToNormalizedTransactions();

    revalidatePath('/dashboard');
    revalidatePath('/import');
    revalidatePath('/cards');
    revalidatePath('/accounts');

    return {
      success: true,
      count: saveRes.count || 0,
      error: null,
    };
  } catch (error: unknown) {
    console.error('App-side database initialization and data migration failed:', error);
    const message = error instanceof Error ? error.message : 'アプリ側でのテーブル作成・正規化処理に失敗しました';
    return { success: false, count: 0, error: message };
  }
}

// Helper functions for normalized lookup records
async function getOrCreateTypeId(name?: string | null): Promise<number | null> {
  if (!name || !name.trim()) return null;
  const trimmed = name.trim();
  const existing = await db.select().from(transactionTypes).where(eq(transactionTypes.name, trimmed));
  if (existing.length > 0) return existing[0].id;
  const inserted = await db.insert(transactionTypes).values({ name: trimmed }).returning();
  return inserted[0].id;
}

async function getOrCreatePaymentMethodId(name?: string | null): Promise<number | null> {
  if (!name || !name.trim()) return null;
  const trimmed = name.trim();
  const existing = await db.select().from(paymentMethods).where(eq(paymentMethods.name, trimmed));
  if (existing.length > 0) return existing[0].id;
  const inserted = await db.insert(paymentMethods).values({ name: trimmed }).returning();
  return inserted[0].id;
}

async function getOrCreateParentCategoryId(name?: string | null): Promise<number | null> {
  if (!name || !name.trim()) return null;
  const trimmed = name.trim();
  const existing = await db.select().from(parentCategories).where(eq(parentCategories.name, trimmed));
  if (existing.length > 0) return existing[0].id;
  const inserted = await db.insert(parentCategories).values({ name: trimmed }).returning();
  return inserted[0].id;
}

async function getOrCreateChildCategoryId(name?: string | null, parentCategoryId?: number | null): Promise<number | null> {
  if (!name || !name.trim()) return null;
  const trimmed = name.trim();

  if (parentCategoryId) {
    const existing = await db
      .select()
      .from(childCategories)
      .where(and(eq(childCategories.name, trimmed), eq(childCategories.parentCategoryId, parentCategoryId)));
    if (existing.length > 0) return existing[0].id;
  } else {
    const existing = await db.select().from(childCategories).where(eq(childCategories.name, trimmed));
    if (existing.length > 0) return existing[0].id;
  }

  const inserted = await db
    .insert(childCategories)
    .values({ name: trimmed, parentCategoryId: parentCategoryId ?? 1 })
    .returning();
  return inserted[0].id;
}

export async function getWorkTransactionsSummary() {
  try {
    const userId = await getSafeUserId();
    const workRows = userId
      ? await db.select().from(transactionsWork).where(eq(transactionsWork.userId, userId))
      : await db.select().from(transactionsWork);

    if (workRows.length === 0) {
      return { data: null, error: null };
    }

    let totalIncome = 0;
    let totalExpense = 0;
    let minDate = workRows[0].date;
    let maxDate = workRows[0].date;

    workRows.forEach((row) => {
      const amount = row.amount || 0;
      if (row.type === '収入' || row.type === 'income') {
        totalIncome += amount;
      } else {
        totalExpense += amount;
      }
      if (row.date < minDate) minDate = row.date;
      if (row.date > maxDate) maxDate = row.date;
    });

    return {
      data: {
        count: workRows.length,
        totalIncome,
        totalExpense,
        balance: totalIncome - totalExpense,
        minDate,
        maxDate,
      },
      error: null,
    };
  } catch (error: unknown) {
    console.error('Failed to summarize transactions_work:', error);
    const message = error instanceof Error ? error.message : 'データ分析に失敗しました';
    return { data: null, error: message };
  }
}

export async function saveWorkToNormalizedTransactions() {
  try {
    const userId = await getSafeUserId();

    // 1. Delete all existing records in normalized transactions table
    if (userId) {
      await db.delete(transactions).where(eq(transactions.userId, userId));
    } else {
      await db.delete(transactions);
    }

    // 2. Fetch all records from transactions_work
    const workRows = userId
      ? await db.select().from(transactionsWork).where(eq(transactionsWork.userId, userId))
      : await db.select().from(transactionsWork);

    if (workRows.length === 0) {
      return { success: false, count: 0, error: 'transactions_work に分析・保存対象のデータが存在しません' };
    }

    let insertedCount = 0;
    for (const row of workRows) {
      const typeId = await getOrCreateTypeId(row.type);
      const paymentMethodId = await getOrCreatePaymentMethodId(row.paymentMethod);
      const parentCategoryId = await getOrCreateParentCategoryId(row.parentCategory);
      const childCategoryId = await getOrCreateChildCategoryId(row.childCategory, parentCategoryId);

      const txItem: typeof transactions.$inferInsert = {
        date: row.date,
        typeId,
        paymentMethodId,
        parentCategoryId,
        childCategoryId,
        amount: row.amount ?? null,
        location: row.location,
        memo: row.memo,
        note: row.note,
        tag: row.tag,
      };

      if (userId) {
        txItem.userId = userId;
      }

      await db.insert(transactions).values(txItem);
      insertedCount++;
    }

    revalidatePath('/dashboard');
    revalidatePath('/import');
    return { success: true, count: insertedCount, error: null };
  } catch (error: unknown) {
    console.error('Failed to save transactions_work into transactions:', error);
    const message = error instanceof Error ? error.message : 'transactions テーブルへの保存に失敗しました';
    return { success: false, count: 0, error: message };
  }
}

export async function getTransactions() {
  try {
    const userId = await getSafeUserId();

    // Strictly query normalized transactions table
    const normalizedList = await db
      .select({
        id: transactions.id,
        userId: transactions.userId,
        date: transactions.date,
        type: transactionTypes.name,
        paymentMethod: paymentMethods.name,
        parentCategory: parentCategories.name,
        childCategory: childCategories.name,
        amount: transactions.amount,
        location: transactions.location,
        memo: transactions.memo,
        note: transactions.note,
        tag: transactions.tag,
        createdAt: transactions.createdAt,
      })
      .from(transactions)
      .leftJoin(transactionTypes, eq(transactions.typeId, transactionTypes.id))
      .leftJoin(paymentMethods, eq(transactions.paymentMethodId, paymentMethods.id))
      .leftJoin(parentCategories, eq(transactions.parentCategoryId, parentCategories.id))
      .leftJoin(childCategories, eq(transactions.childCategoryId, childCategories.id))
      .where(userId ? eq(transactions.userId, userId) : undefined)
      .orderBy(desc(transactions.date), desc(transactions.createdAt));

    const mapped = normalizedList.map((item) => ({
      ...item,
      type: item.type || '支出',
    }));
    return { data: mapped, error: null };
  } catch (error: unknown) {
    console.error('Failed to fetch transactions:', error);
    const message = error instanceof Error ? error.message : 'Failed to fetch transactions';
    return { data: [], error: message };
  }
}

export async function addTransaction(formData: FormData) {
  try {
    const userId = await getSafeUserId();

    const amountStr = formData.get('amount') as string;
    const type = (formData.get('type') as string) || '支出';
    const parentCategory = (formData.get('parentCategory') as string) || (formData.get('category') as string) || 'その他';
    const childCategory = formData.get('childCategory') as string || undefined;
    const date = (formData.get('date') as string) || new Date().toISOString().split('T')[0];
    const memo = formData.get('memo') as string || (formData.get('title') as string) || undefined;
    const location = formData.get('location') as string || undefined;
    const paymentMethod = formData.get('paymentMethod') as string || undefined;
    const note = formData.get('note') as string || undefined;
    const tag = formData.get('tag') as string || undefined;

    const amount = amountStr ? parseInt(amountStr, 10) : null;

    // Resolve lookup IDs
    const typeId = await getOrCreateTypeId(type);
    const paymentMethodId = await getOrCreatePaymentMethodId(paymentMethod);
    const parentCategoryId = await getOrCreateParentCategoryId(parentCategory);
    const childCategoryId = await getOrCreateChildCategoryId(childCategory, parentCategoryId);

    const insertValues: typeof transactions.$inferInsert = {
      date,
      typeId,
      paymentMethodId,
      parentCategoryId,
      childCategoryId,
      amount: amount && !isNaN(amount) ? amount : null,
      location,
      memo,
      note,
      tag,
    };

    const workValues: typeof transactionsWork.$inferInsert = {
      date,
      type,
      paymentMethod,
      parentCategory,
      childCategory,
      amount: amount && !isNaN(amount) ? amount : null,
      location,
      memo,
      note,
      tag,
    };

    if (userId) {
      insertValues.userId = userId;
      workValues.userId = userId;
    }

    await db.insert(transactions).values(insertValues);
    await db.insert(transactionsWork).values(workValues);

    revalidatePath('/dashboard');
    return { success: true, error: null };
  } catch (error: unknown) {
    console.error('Failed to add transaction:', error);
    const message = error instanceof Error ? error.message : '取引の追加に失敗しました';
    return { success: false, error: message };
  }
}

export async function getCardSettingsFromDb() {
  try {
    const list = await db.select().from(cardSettings);
    return { data: list, error: null };
  } catch (error: unknown) {
    console.error('Failed to fetch card settings:', error);
    const message = error instanceof Error ? error.message : 'Failed to fetch card settings';
    return { data: [], error: message };
  }
}

export async function upsertCardSettingInDb(
  cardName: string,
  setting: { isCreditCard?: boolean; closingDay: number; paymentMonthOffset: number; paymentDay: number }
) {
  try {
    if (!cardName || !cardName.trim()) {
      return { success: false, error: 'カード名が無効です' };
    }
    const trimmedCardName = cardName.trim();
    const isCreditCard = setting.isCreditCard ?? true;
    const paymentMethodId = await getOrCreatePaymentMethodId(trimmedCardName);

    // Check existing
    const existing = await db
      .select()
      .from(cardSettings)
      .where(eq(cardSettings.cardName, trimmedCardName));

    if (existing.length > 0) {
      await db
        .update(cardSettings)
        .set({
          paymentMethodId,
          isCreditCard,
          closingDay: setting.closingDay,
          paymentMonthOffset: setting.paymentMonthOffset,
          paymentDay: setting.paymentDay,
          updatedAt: new Date(),
        })
        .where(eq(cardSettings.cardName, trimmedCardName));
    } else {
      await db.insert(cardSettings).values({
        paymentMethodId,
        cardName: trimmedCardName,
        isCreditCard,
        closingDay: setting.closingDay,
        paymentMonthOffset: setting.paymentMonthOffset,
        paymentDay: setting.paymentDay,
      });
    }

    revalidatePath('/cards');
    return { success: true, error: null };
  } catch (error: unknown) {
    console.error('Failed to upsert card setting:', error);
    const message = error instanceof Error ? error.message : 'カード設定の保存に失敗しました';
    return { success: false, error: message };
  }
}

export async function importCsv(formData: FormData) {
  try {
    const userId = await getSafeUserId();

    const file = formData.get('file') as File | null;
    if (!file) {
      return { success: false, error: 'ファイルを選択してください' };
    }

    const csvText = await file.text();
    const rows = parseHouseholdCsv(csvText);

    if (rows.length === 0) {
      return { success: false, error: '有効なデータが見つかりませんでした' };
    }

    // Clear existing records in transactionsWork
    if (userId) {
      await db.delete(transactionsWork).where(eq(transactionsWork.userId, userId));
    } else {
      await db.delete(transactionsWork);
    }

    if (rows.length > 0) {
      for (const row of rows) {
        const workItem: typeof transactionsWork.$inferInsert = {
          date: row.date,
          type: row.type,
          paymentMethod: row.paymentMethod,
          parentCategory: row.parentCategory,
          childCategory: row.childCategory,
          amount: row.amount ?? null,
          location: row.location,
          memo: row.memo,
          note: row.note,
          tag: row.tag,
        };

        if (userId) {
          workItem.userId = userId;
        }

        await db.insert(transactionsWork).values(workItem);
      }
    }

    revalidatePath('/dashboard');
    revalidatePath('/import');
    return { success: true, count: rows.length, error: null };
  } catch (error: unknown) {
    console.error('Failed to import CSV:', error);
    const message = error instanceof Error ? error.message : 'CSVのインポートに失敗しました';
    return { success: false, error: message };
  }
}

export async function updateTransaction(id: number, formData: FormData) {
  try {
    const amountStr = formData.get('amount') as string;
    const type = (formData.get('type') as string) || '支出';
    const parentCategory = (formData.get('parentCategory') as string) || (formData.get('category') as string) || 'その他';
    const childCategory = (formData.get('childCategory') as string) || undefined;
    const date = (formData.get('date') as string) || new Date().toISOString().split('T')[0];
    const memo = (formData.get('memo') as string) || (formData.get('title') as string) || undefined;
    const location = (formData.get('location') as string) || undefined;
    const paymentMethod = (formData.get('paymentMethod') as string) || undefined;
    const note = (formData.get('note') as string) || undefined;
    const tag = (formData.get('tag') as string) || undefined;

    const amount = amountStr ? parseInt(amountStr, 10) : null;

    const typeId = await getOrCreateTypeId(type);
    const paymentMethodId = await getOrCreatePaymentMethodId(paymentMethod);
    const parentCategoryId = await getOrCreateParentCategoryId(parentCategory);
    const childCategoryId = await getOrCreateChildCategoryId(childCategory, parentCategoryId);

    await db
      .update(transactions)
      .set({
        date,
        typeId,
        paymentMethodId: paymentMethodId || null,
        parentCategoryId,
        childCategoryId: childCategoryId || null,
        amount: amount && !isNaN(amount) ? amount : null,
        location: location || null,
        memo: memo || null,
        note: note || null,
        tag: tag || null,
      })
      .where(eq(transactions.id, id));

    await db
      .update(transactionsWork)
      .set({
        date,
        type,
        paymentMethod: paymentMethod || null,
        parentCategory,
        childCategory: childCategory || null,
        amount: amount && !isNaN(amount) ? amount : null,
        location: location || null,
        memo: memo || null,
        note: note || null,
        tag: tag || null,
      })
      .where(eq(transactionsWork.id, id));

    revalidatePath('/dashboard');
    return { success: true, error: null };
  } catch (error: unknown) {
    console.error('Failed to update transaction:', error);
    const message = error instanceof Error ? error.message : '取引の更新に失敗しました';
    return { success: false, error: message };
  }
}

export async function deleteTransaction(id: number) {
  try {
    await db.delete(transactions).where(eq(transactions.id, id));
    await db.delete(transactionsWork).where(eq(transactionsWork.id, id));
    revalidatePath('/dashboard');
    revalidatePath('/cards');
    return { success: true, error: null };
  } catch (error: unknown) {
    console.error('Failed to delete transaction:', error);
    const message = error instanceof Error ? error.message : '取引の削除に失敗しました';
    return { success: false, error: message };
  }
}

export async function updatePaymentMethodName(oldName: string, newName: string) {
  try {
    if (!oldName || !newName || oldName.trim() === newName.trim()) {
      return { success: false, error: '変更前後のカード名を入力してください' };
    }

    const trimmedOld = oldName.trim();
    const trimmedNew = newName.trim();

    // Update paymentMethods lookup table
    const existing = await db.select().from(paymentMethods).where(eq(paymentMethods.name, trimmedOld));
    if (existing.length > 0) {
      await db.update(paymentMethods).set({ name: trimmedNew }).where(eq(paymentMethods.name, trimmedOld));
    }

    await db
      .update(transactionsWork)
      .set({ paymentMethod: trimmedNew })
      .where(eq(transactionsWork.paymentMethod, trimmedOld));

    revalidatePath('/dashboard');
    revalidatePath('/cards');
    return { success: true, error: null };
  } catch (error: unknown) {
    console.error('Failed to update payment method name:', error);
    const message = error instanceof Error ? error.message : 'カード名の更新に失敗しました';
    return { success: false, error: message };
  }
}

// ==========================================
// Bank Accounts & Balances Server Actions
// ==========================================

export async function getBankAccounts() {
  try {
    const userId = await getSafeUserId();

    const list = userId
      ? await db.select().from(bankAccounts).where(eq(bankAccounts.userId, userId)).orderBy(desc(bankAccounts.createdAt))
      : await db.select().from(bankAccounts).orderBy(desc(bankAccounts.createdAt));

    return { data: list, error: null };
  } catch (error: unknown) {
    console.error('Failed to fetch bank accounts:', error);
    const message = error instanceof Error ? error.message : '銀行口座一覧の取得に失敗しました';
    return { data: [], error: message };
  }
}

export async function addBankAccount(accountName: string, bankName?: string, accountNumber?: string) {
  try {
    if (!accountName || !accountName.trim()) {
      return { success: false, error: '口座名を入力してください' };
    }
    const userId = await getSafeUserId();
    const paymentMethodId = await getOrCreatePaymentMethodId(accountName.trim());

    const insertValues: typeof bankAccounts.$inferInsert = {
      paymentMethodId,
      accountName: accountName.trim(),
      bankName: bankName?.trim() || null,
      accountNumber: accountNumber?.trim() || null,
    };

    if (userId) {
      insertValues.userId = userId;
    }

    const inserted = await db.insert(bankAccounts).values(insertValues).returning();

    revalidatePath('/accounts');
    return { success: true, data: inserted[0], error: null };
  } catch (error: unknown) {
    console.error('Failed to add bank account:', error);
    const message = error instanceof Error ? error.message : '銀行口座の追加に失敗しました';
    return { success: false, data: null, error: message };
  }
}

export async function deleteBankAccount(id: number) {
  try {
    await db.delete(bankAccounts).where(eq(bankAccounts.id, id));
    revalidatePath('/accounts');
    return { success: true, error: null };
  } catch (error: unknown) {
    console.error('Failed to delete bank account:', error);
    const message = error instanceof Error ? error.message : '銀行口座の削除に失敗しました';
    return { success: false, error: message };
  }
}

export async function getBankBalances(accountName?: string) {
  try {
    const userId = await getSafeUserId();

    const query = db
      .select({
        id: bankBalances.id,
        userId: bankBalances.userId,
        bankAccountId: bankBalances.bankAccountId,
        accountName: bankAccounts.accountName,
        recordDate: bankBalances.recordDate,
        balance: bankBalances.balance,
        memo: bankBalances.memo,
        createdAt: bankBalances.createdAt,
      })
      .from(bankBalances)
      .innerJoin(bankAccounts, eq(bankBalances.bankAccountId, bankAccounts.id));

    if (accountName) {
      const list = userId
        ? await query.where(and(eq(bankBalances.userId, userId), eq(bankAccounts.accountName, accountName))).orderBy(desc(bankBalances.recordDate), desc(bankBalances.createdAt))
        : await query.where(eq(bankAccounts.accountName, accountName)).orderBy(desc(bankBalances.recordDate), desc(bankBalances.createdAt));
      return { data: list, error: null };
    }

    const list = userId
      ? await query.where(eq(bankBalances.userId, userId)).orderBy(desc(bankBalances.recordDate), desc(bankBalances.createdAt))
      : await query.orderBy(desc(bankBalances.recordDate), desc(bankBalances.createdAt));

    return { data: list, error: null };
  } catch (error: unknown) {
    console.error('Failed to fetch bank balances:', error);
    const message = error instanceof Error ? error.message : '口座残高履歴の取得に失敗しました';
    return { data: [], error: message };
  }
}

export async function addBankBalanceRecord(accountName: string, balance: number, recordDate: string, memo?: string) {
  try {
    if (!accountName || !accountName.trim()) {
      return { success: false, error: '口座名が無効です' };
    }
    if (isNaN(balance)) {
      return { success: false, error: '有効な残高金額を入力してください' };
    }

    const userId = await getSafeUserId();

    // Find bankAccountId by accountName or create bankAccount
    const existingAccounts = await db
      .select()
      .from(bankAccounts)
      .where(eq(bankAccounts.accountName, accountName.trim()));

    let bankAccountId: number;
    if (existingAccounts.length > 0) {
      bankAccountId = existingAccounts[0].id;
    } else {
      const addRes = await addBankAccount(accountName.trim());
      if (!addRes.success || !addRes.data) {
        return { success: false, error: '銀行口座の自動登録に失敗しました' };
      }
      bankAccountId = addRes.data.id;
    }

    const insertValues: typeof bankBalances.$inferInsert = {
      bankAccountId,
      recordDate: recordDate || new Date().toISOString().split('T')[0],
      balance,
      memo: memo?.trim() || null,
    };

    if (userId) {
      insertValues.userId = userId;
    }

    await db.insert(bankBalances).values(insertValues);

    revalidatePath('/accounts');
    return { success: true, error: null };
  } catch (error: unknown) {
    console.error('Failed to add bank balance record:', error);
    const message = error instanceof Error ? error.message : '残高記録の追加に失敗しました';
    return { success: false, error: message };
  }
}

export async function deleteBankBalanceRecord(id: number) {
  try {
    await db.delete(bankBalances).where(eq(bankBalances.id, id));
    revalidatePath('/accounts');
    return { success: true, error: null };
  } catch (error: unknown) {
    console.error('Failed to delete bank balance record:', error);
    const message = error instanceof Error ? error.message : '残高記録の削除に失敗しました';
    return { success: false, error: message };
  }
}
